server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
    database: 2
    password: dongyang106

redisson:
  single-server-config:
    address: 127:0:0:1:6379

lua:
  capacity: 2

logging:
  level:
    root: info